/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PessoaController;
import model.Pessoa;
import javax.swing.*;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author gabriel
 */
public class ServidorView extends javax.swing.JFrame {

    private DefaultListModel<String> modelLista;
    private final PessoaController controller = new PessoaController();

    /**
     * Creates new form ServidorView
     */
    public ServidorView() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelLista = new DefaultListModel<>();
        listPessoas.setModel(modelLista);

       //mostra os salvos 
        atualizarListaGrafica();
        
        // Inicia a escuta do servidor em uma thread separada, para não
        // travar a interface (accept() é bloqueante).
        new Thread(this::iniciarServidor).start();
}
        
    private void iniciarServidor() {
            try {
                int porta = 50000;
                ServerSocket servidor = new ServerSocket(porta);
                log("Servidor ouvindo a porta: " + porta);

                //Loop para aceitar conexões contínuas
                while (true) {
                    Socket cliente = servidor.accept();
                    log("Cliente conectado no IP: " + cliente.getInetAddress().getHostAddress());
                    
                    new Thread(() -> atenderCliente(cliente)).start();
                 }
            } catch(Exception e){
                             log("Erro no servidor: " + e.getMessage());
}
}

   private void atenderCliente(Socket cliente) {
        try (Socket socket = cliente;
             ObjectOutputStream saida = new ObjectOutputStream(socket.getOutputStream())) {
 
            saida.flush();
            ObjectInputStream entrada = new ObjectInputStream(socket.getInputStream());
 
            // Desserializa o objeto recebido do cliente
            Pessoa pRecebida = (Pessoa) entrada.readObject();
            log("Recebido do cliente: " + pRecebida.getNome());
 
            // Recebe o objeto e envia para as regras de negócio no controller
            // (o controller já se encarrega de salvar em disco se for novo)
            Pessoa pProcessada = controller.processarCadastro(pRecebida);
 
            // Envia o objeto processado de volta para o cliente
            saida.writeObject(pProcessada);
            saida.flush();
 
            // Atualiza a listagem de pessoas na interface do servidor
            atualizarListaGrafica();
 
        } catch (Exception e) {
            log("Erro ao atender cliente: " + e.getMessage());
        }
    }
 
    private void log(String msg) {
        SwingUtilities.invokeLater(() -> txtLog.append(msg + "\n"));
    }
 
    private void atualizarListaGrafica() {
        SwingUtilities.invokeLater(() -> {
            modelLista.clear();
            for (Pessoa p : controller.getListaPessoas()) {
                modelLista.addElement(p.toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPessoas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor - Cadastro");

        jSplitPane1.setResizeWeight(0.5);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Log de Eventos"));

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        jSplitPane1.setRightComponent(jScrollPane1);
        jScrollPane1.getAccessibleContext().setAccessibleName("Eventos");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoas Cadastradas"));
        jScrollPane2.setViewportView(listPessoas);

        jSplitPane1.setLeftComponent(jScrollPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServidorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList<String> listPessoas;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
